# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: .clang-format
    -   id: check-added-large-files

# clang-format
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.1
    hooks:
    -   id: clang-format

# isort
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)


# black
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black

# flake8
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
