version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks: 
      - admin
    command: sleep infinity

  client:
    build:
      context: nw_node
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../build/bin:/home/user/mux
    networks: 
      - client_server
      - admin    
    command: sleep infinity

  #node:
  #  build:
  #    context: nw_node
  #    dockerfile: Dockerfile
  #  restart: unless-stopped
  #  volumes:
  #    - ../build/bin:/home/user/mux
  #  networks: 
  #    - client_server
  #    - admin    
  #  command: sleep infinity
    
  server:
    build:
      context: nw_node
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../build/bin:/home/user/mux
    networks: 
      - client_server
      - admin
    command: sleep infinity

networks:
  admin:
  client_server:
