name: build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/valsaa/mux/mux-devcontainer
          runCmd: |
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-18 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-18 -S/workspaces/mux -B/workspaces/mux/ci-build -G "Unix Makefiles"
            cmake --build /workspaces/mux/ci-build --config Debug --target all

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ${{ github.workspace }}/ci-build/bin/*