name: build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mux/mux-devcontainer
          runCmd: |
            cmake -S . -B ./build/
            cmake --build ./build/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ./build/bin/mux